### ISSUE TITLE
[ResourceRevamp] Add item identifier

### ISSUE THREAD

**Issue by AsherGlick** [AsherGlick/ResourceCalculator#81]
For actively developed games, item names can change over time. This can cause several types of issues because we key our items off of their names. To solve this an immutable resource id should be added.

The two major issues are
1) Existing URLs will break because the name of the item is different. (referenced in #34)
2) Item recipes all need to be updated to the new name and can easily be forgotten or skipped

These examples will assume that #78 has already been completed
```yaml
resources:
  - name: Stone
    recipes:
    - recipe_type: Raw Resource
    - output: 1
      recipe_type: Smelting
      requirements:
        Cobblestone: -1
        Fuel: -1

  - name: Granite
    recipes:
    - recipe_type: Raw Resource
    - output: 1
      recipe_type: Crafting
      requirements:
        Diorite: -1
        Nether Quartz: -1
```
Becomes
```yaml
resources:
  - name: Stone
    id: 1
    recipes:
    - recipe_type: Raw Resource
    - output: 1
      recipe_type: Smelting
      requirements:
        Cobblestone: -1
        Fuel: -1

  - name: Granite
    id: 2
    recipes:
    - recipe_type: Raw Resource
    - output: 1
      recipe_type: Crafting
      requirements:
        Diorite: -1
        Nether Quartz: -1
```
If an item is deleted from the recipe list the item id will be persisted so no other resource uses it
```yaml
deprecated_ids: [2]
resources:
  - name: Stone
    id: 1
    recipes:
    - recipe_type: Raw Resource
    - output: 1
      recipe_type: Smelting
      requirements:
        Cobblestone: -1
        Fuel: -1
```

A linter will be unable to catch instances of removing or altering an id, however it may be possible to detect the deletion of an id during a presumit or premerge check in github actions.
