### ISSUE TITLE
[ResourceRevamp] Remove Negative Requirement Values

### ISSUE THREAD

**Issue by AsherGlick** [AsherGlick/ResourceCalculator#82]
A relic from the original iteration of the code is that all of the requirements are negative values. This is due to how the solver works, by "adding" the negative requirements each iteration.

From the perspective of the resource list this makes no sense however. All the numbers should just be positive values to avoid having to add in all these extra `-` signs.

```yaml
  Anvil:
    recipes:
    - output: 1
      recipe_type: Crafting
      requirements:
        Block of Iron: -3
        Iron Ingot: -4
    - recipe_type: Raw Resource
```
becomes
```yaml
  Anvil:
    recipes:
    - output: 1
      recipe_type: Crafting
      requirements:
        Block of Iron: 3
        Iron Ingot: 4
    - recipe_type: Raw Resource
```
This will either require a change in the front end solver (ideal solution), or a change in the build script to emulate the negative values in the bundle that is sent to the front end.
