### ISSUE TITLE
Format of Yaml

### ISSUE THREAD

**Issue by Orgams** [AsherGlick/ResourceCalculator#9]
Hello,

I am creating a scrapper for the Astroneers Wiki to automatically generate the file "resources.yaml" and the linked images.

When generating the yaml (lib pyyaml) I do not get a format that the generation script of the ResourceCalculator site accepts:
```yaml
- Resin:
    recipes:
      output: 1
      recipe_type: Raw Resource
      requirements:
        Resin: 0
```
Here is the piece of code for my tests:
```python
import yaml
astro = [
	{
	'Resin' :
		{
		'recipes' :
			{'output' : 1,
				'recipe_type' : 'Raw Resource',
				'requirements' : {
					'Resin' : 0
				}
			}
		}
	}
]
print(yaml.dump(astro))
```
If you have an idea where it comes from I would like to help out, otherwise thank you for your time!

**Comment by AsherGlick** [comment]
This sounds fantastic and I cant wait to see your work.
It can be difficult to understand the underlying structure of YAML sometimes, it does not help that resource calculator takes advantage of ordered  dicts too. But the structure you are looking for is:


```python3
import yaml
astro = {
	"index_page_display_name": "Astroneer",
	"resources": {
		"Resin": {
			'recipes': [
				{
					'output' : 1,
					'recipe_type' : 'Raw Resource',
					'requirements' : {
						'Resin' : 0
					}
				}
			]
		}
	}
}

print(yaml.dump(astro))
```

which generates 
```yaml
index_page_display_name: Astroneer
resources:
  Resin:
    recipes:
    - output: 1
      recipe_type: Raw Resource
      requirements:
        Resin: 0
```


Hope that helps!
